build:
  image: alpine

publish:
  docker:
    username: $$DOCKER_USERNAME 
    password: $$DOCKER_PASSWORD
    email: $$DOCKER_EMAIL
    repo: rzarouali/alpine-serverspec
    tag: $${BRANCH/master/latest}
    file: Dockerfile
    when:
      repo: xinity/alpine-serverspec
      branch: [develop, master]

notify:
  gitter:
     webhook: https://webhooks.gitter.im/e/$$GITTER_WEBHOOK

plugin:
  name: Docker
  desc: Build and Publish images to a Docker registry.
  type: publish
  image: plugins/drone-docker
  labels:
    - docker
    - image
    - container

plugin:
  name: Gitter
  desc: Build and Publish images to a Docker registry.
  type: publish
  image: plugins/drone-gitter
  labels:
    - notify
    - gitter
    - container
